---
- name: Remove snap installs
  when:
    - snapd_purge
  register: snap_uninstall
  changed_when: "'removed' in snap_uninstall.stdout"
  ansible.builtin.shell: |
    set -o pipefail
    if which snap >/dev/null; then
      snap list | tail -n +2 | awk '{system("snap remove " $1 " --purge")}'
    fi
  args:
    executable: /bin/bash
  tags:
    - snapd

- name: Purge snapd package
  when:
    - snapd_purge
  ansible.builtin.apt:
    name: snapd
    purge: true
    state: absent
  tags:
    - snapd

- name: Drop snap directories
  when:
    - snapd_purge
  loop:
    - /snap
    - /root/snap
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  tags:
    - snapd

- name: Pin any version
  ansible.builtin.copy:
    content: |
      Explantion: Pin added by snapd role
      Package: snapd
      Pin: release a=*
      Pin-Priority: -10
    dest: /etc/apt/preferences.d/snapd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - snapd

...
