---
- name: Remove snap installs
  when: snapd_purge
  register: snap_uninstall
  changed_when: "'removed' in snap_uninstall.stdout"
  shell:
    cmd: snap list | tail -n +2 | awk '{system("snap remove " $1 " --purge")}'
  tags:
    - snapd

- name: Purge snapd package
  when: snapd_purge
  apt:
    name: snapd
    purge: True
    state: absent
  tags:
    - snapd

- name: Drop snap directories
  when: snapd_purge
  loop:
    - /snap
    - /root/snap
  file:
    path: "{{ item }}"
    state: absent
  tags:
    - snapd

- name: Pin any version
  copy:
    content: |
      Explantion: Pin added by snapd role
      Package: snapd
      Pin: release a=*
      Pin-Priority: -10
    dest: /etc/apt/preferences.d/snapd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - snapd

...
