# Standards: 1.2
---
- name: Purge snapd package
  when: snapd_purge
  apt:
    name: snapd
    purge: True
    state: absent
  tags:
    - snapd

- name: Drop snap directories
  when: snapd_purge
  loop:
    - /snap
    - /root/snap
  file:
    path: "{{ item }}"
    state: absent
  tags:
    - snapd

...
